remote_theme: pages-themes/minimal@v0.2.0
title: Hi! I'm David Zegarra
description: A professional in Electronics with +20 years in the field. These days I navigate the embedded circuit and web interface domains, building at the intersection of embedded systems, IoT/RFID, and web development. An advocate of good documentation, because it's what keeps a project alive.
